# @package _global_

data_module:
  _target_: 'data.IRDataModule'
  name: "paired"
  dual_pixel: False
  num_channels: 3
  train:
    dataset: gopro
    batch_size: ${batch_size}
    num_workers: ${num_workers}
    num_channels: ${data_module.num_channels}
    dual_pixel: ${data_module.dual_pixel}
    patch_size: ${patch_size}
    num_patches: 1
  val:
    dataset: gopro
    batch_size: 1
    num_workers: ${num_workers}
    num_channels: ${data_module.num_channels}
    dual_pixel: ${data_module.dual_pixel}
  test: null
