# @package _global_

data_module:
  _target_: 'data.IRDataModule'
  name: "sr"
  scale: 2
  num_channels: 3
  train:
    dataset: div2k_extended
    batch_size: ${batch_size}
    num_workers: ${num_workers}
    num_channels: ${data_module.num_channels}
    scale: ${data_module.scale}
    lr_patch_size: ${patch_size}
    num_patches: 1
    ignored_boundary_size: ${data_module.scale}
    load_lr: True # False: generate LR images online
  val:
    dataset: set5+set14+b100+urban100+manga109+div2k
    batch_size: 1
    num_workers: ${num_workers}
    num_channels: ${data_module.num_channels}
    scale: ${data_module.scale}
  test: null
