# @package _global_

metric:
  train_psnr:
    _target_: torchmetrics.PeakSignalNoiseRatio
    data_range: 1.0

  val_psnr:
    _target_: utils.metrics.psnr.PeakSignalNoiseRatio
    data_range: 1.0
  val_ssim:
    _target_: utils.metrics.ssim.StructuralSimilarityIndexMeasure
    data_range: 1.0
