# @package _global_

metric:
  train_psnr:
    _target_: torchmetrics.PeakSignalNoiseRatio
    data_range: 1.0

  val_psnr:
    _target_: utils.metrics.psnr.PeakSignalNoiseRatio
    data_range: 1.0
  val_psnr_y:
    _target_: utils.metrics.psnr.PeakSignalNoiseRatio
    data_range: 1.0
    channel: "y"
  val_ssim:
    _target_: utils.metrics.ssim.StructuralSimilarityIndexMeasure
    data_range: 1.0
  val_ssim_y:
    _target_: utils.metrics.ssim.StructuralSimilarityIndexMeasure
    data_range: 1.0
    channel: "y"
  # val_lpips:
  #   _target_: torchmetrics.image.lpip.LearnedPerceptualImagePatchSimilarity
  val_lpips:
    _target_: utils.metrics.lpips.LearnedPerceptualImagePatchSimilarity
    # only used during test. only for RGB images
  val_niqe:
    _target_: utils.metrics.niqe.NaturalImageQualityEvaluator
    # only used during test.
