# @package _global_
model:
  name: "grl_base_bsr"
  model_g:
    _target_: models.networks.grl.GRL
    name: "grl_base"
    upscale: 4
    in_channels: 3
    embed_dim: 180
    img_range: 1.
    img_size: ${patch_size}
    upsampler: nearest+conv
    depths: [4, 4, 8, 8, 8, 4, 4]
    num_heads_window: [3, 3, 3, 3, 3, 3, 3]
    num_heads_stripe: [3, 3, 3, 3, 3, 3, 3]
    window_size: 8
    stripe_size: [8, null]
    stripe_groups: [null, 4]
    stripe_shift: True
    mlp_ratio: 2
    qkv_proj_type: "linear"
    anchor_proj_type: "avgpool"
    anchor_one_stage: True
    anchor_window_down_factor: 4
    out_proj_type: "linear"
    conv_type: "1conv"
    init_method: "n"
    fairscale_checkpoint: False
    offload_to_cpu: False
    double_window: False
    stripe_square: False
    separable_conv_act: True
    local_connection: True
    use_buffer: True
    use_efficient_buffer: True
  model_d:
    _target_: models.aux_archs.discriminator.UNetDiscriminatorSN
    num_in_ch: 3
    num_feat: 64
    skip_connection: True
